### ISSUE TITLE
Use with JsonSerializer

### ISSUE THREAD

**Issue by mrstebo** [DSaunders/Nancy.JsonPatch#1]
I am using a JsonSerializer to convert my models property names in to snake case. But if I try and do any of the operations using the snake-cased format it says it cannot find the path.

I will try and get a PR ready for adding in this feature.

**Comment by mrstebo** [comment]
Added a property resolver class so we can specify the convert the received property name in the the "Actual" property name.

[See here](https://github.com/mrstebo/Nancy.JsonPatch/blob/property-resolver/src/Nancy.JsonPatch/PropertyResolver/JsonPatchPropertyResolver.cs)

**Comment by DSaunders** [comment]
Hi @mrstebo. This looks brilliant thanks, if you're happy to submit a PR I'll merge it in.

**Comment by mrstebo** [comment]
I will also write some docs on how to use the `IJsonPatchPropertyResolver` and submit that soon.
